# Generated by Django 4.2.6 on 2023-10-08 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('long', models.DecimalField(decimal_places=16, max_digits=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_ticket_id', models.CharField(max_length=50, unique=True)),
                ('travel_date', models.DateField()),
                ('travel_mode', models.CharField(choices=[('Car', 'Car'), ('Flight', 'Flight'), ('Train', 'Train')], max_length=30)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_phone', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('seat_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_tickets', to='ticket.location')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_tickets', to='ticket.location')),
            ],
        ),
    ]
